variable name {}
variable project {}
variable network_name {}
variable app_instance_type {}
variable enable_autoscaling {}
variable env {}
variable region {}
variable source_image {}
variable db_name {}
variable db_user {}
variable db_password {}
variable db_ip {}
